### ISSUE TITLE
Cast Response body instead of reading content

### ISSUE THREAD

**Issue by sagikazarmark** [jolicode/jane#14]
Currently the generated code calls `getContents` on the body. However, this method only returns the content of the stream from the current pointer. If a HTTPlug plugin modifies the response, this method could return nothing or part of the stream while casting the stream to string always returns the whole body.

**Comment by joelwurtz** [comment]
Jane OpenApi issue :)

**Comment by sagikazarmark** [comment]
Of course it is.
