### ISSUE TITLE
Send body as JSON/XML

### ISSUE THREAD

**Issue by sagikazarmark** [jolicode/jane#15]
Currently I can't find a way to send body parameter encoded as JSON/XML.

Is it possible?

**Comment by joelwurtz** [comment]
It's possible in JSON not in in XML, you need to specify a schema in a body parameter, if the schema is a reference then it will use the serializer to encode it in the body of the request as JSON

**Comment by sagikazarmark** [comment]
Cool, just found it, thanks.

Regarding body: in other cases, it seems that form data is sent in the body, even if body parameter is not specified. Is it a good idea?

**Comment by joelwurtz** [comment]
Form data will be empty if there is no parameter, so it's ok for the moment.

**Comment by sagikazarmark** [comment]
Thanks!
