### ISSUE TITLE
Support JSON schema formats

### ISSUE THREAD

**Issue by sagikazarmark** [jolicode/jane#16]
As per jolicode/jane-openapi#10

Support special JSON schema formats, like DateTime, which is represented as a special string format.

**Comment by sagikazarmark** [comment]
Well, I tried doing this, but failed at about half way (I think). I don't think I will be able to pick this up in the near future, but it would be a really nice feature, so I will leave this to you. :smile:

**Comment by joelwurtz** [comment]
I need it also, so expect this soon :)

**Comment by joelwurtz** [comment]
(At least for the date time)

**Comment by sagikazarmark** [comment]
Yupiiii

**Comment by sagikazarmark** [comment]
Any update?

**Comment by joelwurtz** [comment]
Ok for datetime other formats don't have specific type in PHP so we should keep them as string.

They will be handled when generating validations.

**Comment by sagikazarmark** [comment]
Agreed, datetime format is the most common one.
