### ISSUE TITLE
General property exists usage

### ISSUE THREAD

**Issue by sagikazarmark** [jolicode/jane#27]
It is not a good idea after all. For example date time values should not be formatted, if the value is null. In general: if the value is nullable, property exists is fine, since null is a value there. If it is not nullable, we should return to isset as null is not a value, but indication of lack of value in this case.

**Comment by sagikazarmark** [comment]
I think this is connected to #26. Once this gets solved, #26 will be solved as well.

**Comment by joelwurtz** [comment]
> If it is not nullable, we should return to isset as null is not a value, but indication of lack of value in this case.

Yes but that would mean your data is invalid according to the schema. It the property is not nullable and you have a null value, then in fact it is nullable :), so i don't think i should handle this here, property_exists is fine IMO

**Comment by sagikazarmark** [comment]
I think we have to cases here:

1. Data is nullable, which means null is a valid value from the API.
2. Data is not nullable, which means the lack of data. In this case, internally, the value is still converted to null (more precisely converted to nothing and falls back to default).

The difference is that while null might be a valid value, lack of data indicates that you either have to fall back to a default or you will get null from the normalized object.

For example: A last modified timestamp MIGHT be null, if there was no modification. But if you modify it, it must not be null anymore. In this case null is not a value, but the lack of data.

**Comment by joelwurtz** [comment]
If there is lack of data then the property must not be present in the json and not be null (property_exists is only use on the denormalization size) also this null thing is already done in the normalization side (if it's null it does not put the value in the array / stdClass ).

**Comment by sagikazarmark** [comment]
Okay, I can live with this as a won't fix. Although in that case in the schema I have to make in theory non-nullable values to nullable ones. (I admit, the API I am using this for is not the best I've ever seen ;) )

In that case, #26 is still an issue.

**Comment by joelwurtz** [comment]
Yes, some API will put values everywhere even if there is a lack of data, however dealing with this kind of value should be on the user side (don't want to support such a hack on this, as it would be unmaintainable in the futur and user would be used to a bad design / approach)

**Comment by sagikazarmark** [comment]
Agreed.

**Comment by sagikazarmark** [comment]
I think you should label this as wontfix for future reference.
