### ISSUE TITLE
Generated classes should use the right type-hints

### ISSUE THREAD

**Issue by fago** [jolicode/jane#32]
When having properties with some type MyType, like 

```
                "customFields": {
                    "type": "MyCustomFields"
                },
```
the model for MyCustomFields is generated, but it's not used in the generated class for the model of MyType.

**Comment by joelwurtz** [comment]
Hey,

It's not a valid json schema,`in order to link a property to an existing class you should use something like this : 

```json
"customFields": {
     "$ref": "MyCustomFields"
},
